[package]
name = "fl-discord-rpc"
version = "0.1.0"
edition = "2021"
author = "s0uthview"

[dependencies]
chrono = "0.4.37"
discord-rpc-client = "0.4.0"
sysinfo = "0.30.10"
tokio = { version = "1.37.0", features = ["full"] }
